[cosmic-ray]
module-path = "HumanEval_152.py"
python-version = "3.8"
test-command = "python -m unittest discover -s  test_HumanEval_152"
timeout = 10

[cosmic-ray.distributor]
name = "local"

[cosmic-ray.python]
pythonpath = ["."]
