[cosmic-ray]
module-path = "./"
python-version = "3.8"
test-command = "python -m unittest discover -s tests"
timeout = 30
operator = "core/ReplaceUnaryOperator"

[cosmic-ray.test-runner]
name = "unittest"
args = ["test_calculator"]

[cosmic-ray.distributor]
name = "local"
